version: '3'
services:
  webservice:
    image: "test/webservice:latest"
    ports:
      - "3000:3000"
    container_name: webservice
    depends_on:
      - redis
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./web-root:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - webservice
  redis:
    image: "redis:alpine"
    container_name: redis
  prometheus:
    image: "prom/prometheus:latest"
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
  #nginx-exporter:
  #  image: "nginx/nginx-prometheus-exporter:latest"
  #  environment:
  #    - nginx.scrape-uri=http://webserver:8080/stub_status
