version: "3.3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    ports:
      - "9090:9090"
    volumes: 
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    networks: 
      - prometheus-network
  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackboxprober
    ports:
      - "9115:9115"
    volumes: 
      - ./blackbox-config/config.yml:/etc/blackbox_exporter/config.yml 
    networks: 
      - prometheus-network
  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    ports:
      - "9100:9100"
    networks: 
      - prometheus-network
networks:
  prometheus-network:
    driver: bridge 