version: "3.3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    ports:
      - "80:9090"
    volumes: 
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    networks: 
      - prometheus-network
networks:
  prometheus-network:
    driver: bridge 