version: "3.3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    ports:
      - "9090:9090"
    volumes: 
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    networks: 
      - prometheus-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    ports: 
      - "80:3000"
    volumes:
      - /var/lib/grafana
    networks: 
      - prometheus-network
networks:
  prometheus-network:
    driver: bridge 